### PR TITLE
Added time and altitude options to to_gpx functions

### LINKED ISSUE #5: csv_to_gpx does not use elevation and time
* gpx_converter version:
* Python version:3.8
* Operating System:Ubuntu20.04

### Description
When converting csv_to_gpx only latitude and longitude are taking in consideration. What about elevation, time, extensions?

I see that when converting from gpx to csv those are taking in consideration

### PR DESCRIPTION
**Pull request by Eeelco**
This should fix #5. I set the default values of the new columns to None in order to not break existing workflows.

### CODE REVIEW

**Comment by nidhaloff** [comment]
@Eeelco Looks good, thanks for the PR. Can you consider adding some unit tests under the tests folder? this has been already described in the contribution guide.

**Comment by Eeelco** [comment]
@nidhaloff Thanks for the feedback. I implemented the tests as you suggested. I also implemented a test for the gpx_to_excel function, which showed that this function had problems when the input contained timezone data. This should now be fixed.

The pd.Timestamp function seemed to have a problem with the timeformat for .json files being in the epoch format. Converting a json to gpx and back again would result in the last 6 digits of the timestamp being cut-off somehow. Due to this, I changed the gpx_to_json function to also export time in the ISO format, which has the added benefit of the different formats being more uniform.

**Comment by nidhaloff** [comment]
@Eeelco Good finding! Thanks for your work ;)

**Comment by Eeelco** [comment]
@nidhaloff No problem, thanks for your help! Would you mind labelling the contribution as hacktoberfest-accepted?

**Comment by nidhaloff** [comment]
@Eeelco Done

**Pull request merged**
