### PR TITLE
Added time and elevation columns to dataframe

### PR DESCRIPTION
**Pull request by Riemer17**
Hi, now when a gpx file has time and/or altitude data the data is saved in the dictionary, dataframe etcetera. Only when there is no time and/or altitude data the whole columns if full of None's. I don't know if this is desirable, but I haven't found a way to fix it.

### CODE REVIEW

**Comment by nidhaloff** [comment]
Hi, @Riemer17  Thanks for the issue and PR. However, I'm not quite sure if this will work as expected. Did you test this with examples that contain time and altitude values?

**Comment by Riemer17** [comment]
I tested it with one example, but it might need more testing. I will do some more testing

**Comment by nidhaloff** [comment]
@Riemer17 can you please show the example you tested with. Sometimes the time value is added differently in some gpx files, which makes me wonder if your code will work for all different files

**Comment by Riemer17** [comment]
You were right it wasn't exactly good when you looked at it. I hope I fixed it in my last commit. 

I used this gpx file for example:
[Oefenwedstrijd_Amsterdamse_bos.zip](https://github.com/nidhaloff/gpx-converter/files/5719731/Oefenwedstrijd_Amsterdamse_bos.zip)

**Comment by nidhaloff** [comment]
@Riemer17 This looks better but I'm still not sure if the implementation will work for all gpx files. I will accept your PR though ;), however, I hope you can test this further and maybe check new issues that will derive from it.

**Pull request merged**
